namespace Tickefy.Application.Abstractions.Services
{
    /// <summary>
    /// Defines contract requirements for cryptographic password hashing and verification using industry-standard key derivation algorithms.
    /// </summary>
    public interface IPasswordHasher
    {
        /// <summary>
        /// Transforms a plain-text password into a cryptographically secure, salted hash string suitable for persistent database storage.
        /// </summary>
        /// <param name="password">
        /// The raw, unhashed plain-text password provided by the user. Must not be null or empty; callers should ensure passwords meet minimum entropy and length requirements prior to hashing.
        /// </param>
        /// <returns>
        /// A string containing the derived password hash and encoded cryptographic salt (e.g., using BCrypt or PBKDF2 formatting).
        /// </returns>
        /// <remarks>
        /// Hashing is an intentionally computationally expensive operation designed to resist brute-force and rainbow table attacks. Avoid executing this method on UI or synchronous I/O threads when under heavy load.
        /// </remarks>
        public string HashPassword(string password);

        /// <summary>
        /// Evaluates whether a candidate plain-text password matches an existing stored cryptographic password hash.
        /// </summary>
        /// <param name="password">
        /// The candidate plain-text password submitted during authentication. Passing null or an empty string will evaluate to false without throwing an exception.
        /// </param>
        /// <param name="hash">
        /// The stored cryptographic hash string previously generated by <see cref="HashPassword"/>. Must be a validly formatted hash; passing a malformed hash string may throw a cryptographic formatting exception.
        /// </param>
        /// <returns>
        /// <see langword="true"/> if the candidate password successfully verifies against the salted hash; otherwise, <see langword="false"/>.
        /// </returns>
        /// <remarks>
        /// This verification comparison is implemented using constant-time equality checks where supported by the algorithm to prevent timing side-channel attacks.
        /// </remarks>
        public bool VerifyPassword(string password, string hash);
    }
}
