using Tickefy.Domain.Common.UserRole;
using Tickefy.Domain.RefreshTokens;

namespace Tickefy.Application.Abstractions.Services
{
    /// <summary>
    /// Defines contract requirements for cryptographic token generation, authentication payload signing, and refresh token issuing.
    /// </summary>
    public interface ITokenService
    {
        /// <summary>
        /// Asynchronously generates a cryptographically signed JSON Web Token (JWT) encapsulating the identity claims of an authenticated user.
        /// </summary>
        /// <param name="id">
        /// The unique primary key GUID of the authenticated user. Must represent a valid user record; passing an empty GUID will embed invalid subject claims in the token payload.
        /// </param>
        /// <param name="login">
        /// The unique login username of the authenticated user. Used as the principal identity identifier within standard token claims; must not be null or whitespace.
        /// </param>
        /// <param name="role">
        /// The assigned role authorization level of the user, embedded into the token claims to facilitate downstream role-based access control (RBAC).
        /// </param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>
        /// A task representing the asynchronous token signing operation. The task result contains the Base64-encoded, digitally signed JWT access token string.
        /// </returns>
        /// <remarks>
        /// Callers must ensure that token expiration settings configured in system options are appropriate for the security level of the application, as issued JWTs cannot be revoked without maintaining a token blacklist.
        /// </remarks>
        public string GetToken(Guid id, string login, UserRoles role);

        /// <summary>
        /// Generates a high-entropy, cryptographically secure random string suitable for use as a long-lived OAuth refresh token.
        /// </summary>
        /// <returns>
        /// A Base64-encoded string derived from a cryptographically random byte sequence.
        /// </returns>
        /// <remarks>
        /// Refresh tokens generated by this method do not contain internal identity claims or expiration timestamps; they must be stored securely alongside their associated metadata in a persistent repository.
        /// </remarks>
        public string GenerateRefreshToken();
    }
}
