name: Build and deploy a container to an Azure Web App

env:
    AZURE_WEBAPP_NAME: tickefy-api

on:
    workflow_run:
        workflows: ["Test"]
        types:
            - completed
        branches:
            - dev
    workflow_dispatch:

jobs:
    build:
        if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
        permissions:
             contents: read
             packages: write

        uses: ./.github/workflows/docker-build.yml
        with:
            image_tag: ${{ github.event.workflow_run.head_sha || github.sha }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: none

        steps:
            - name: Lowercase the repo name and username
              run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  images: 'ghcr.io/${{ env.REPO }}:${{ github.event.workflow_run.head_sha || github.sha }}'
